### ISSUE TITLE
Prosis Pro Web- Password Reset

### ISSUE THREAD

**Issue by kbt1** [stellaballa/ProsisProDesktop#1]
to eliminate some confusion with our members and unnecessary phone calls
can we change some wording:
Change wording from Password Reset to **Change Password**
At the bottom by the reset button, add  **Note: After Password has been changed, login in with New Password**

Let me know if this is easily done.
Thank you
Karen

**Comment by stellaballa** [comment]
@SagarPC  please update.

**Comment by SagarPC** [comment]
@kbt1 We updated message and now it will look like below. We uploaded same to the live.

![image](https://user-images.githubusercontent.com/31076567/63422547-2c26ff80-c428-11e9-8060-92d70ed0d197.png)

**Comment by kbt1** [comment]
Perfect, thank you!
